'use client';
import { useState } from 'react';
import { apiFetch, useApi } from '@/lib/api-client';
import { fmtDate, timeAgo, titleCase } from '@/lib/utils';
import { PageHeader, LoadingRows, ErrorBox } from '@/components/shared/page';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Badge } from '@/components/ui/badge';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';

const SCOPES = ['events:write', 'customers:write', 'customers:read', 'audiences:read', 'audiences:write', 'audiences:activate', 'sync:read', 'suppression:write', 'campaigns:write', 'analytics:read'];
export default function SettingsPage() {
  const me = useApi<any>('/api/v1/me'); const keys = useApi<{ data: any[] }>('/api/v1/settings/api-keys'); const ret = useApi<{ data: any[] }>('/api/v1/settings/retention'); const members = useApi<{ data: any[] }>('/api/v1/settings/members');
  const [keyName, setKeyName] = useState(''); const [scopes, setScopes] = useState<string[]>(['events:write']); const [created, setCreated] = useState<{ key: string } | null>(null); const [err, setErr] = useState<string | null>(null);
  const [retDraft, setRetDraft] = useState<Record<string, number>>({}); const [retMsg, setRetMsg] = useState<string | null>(null);
  const [inv, setInv] = useState({ email: '', name: '', role: 'ANALYST', password: '' }); const [invMsg, setInvMsg] = useState<string | null>(null);
  return (<div>
    <PageHeader title="Settings" description="Organization, access control, API keys and retention. Only ADMIN+ can change these." />
    <Tabs defaultValue="org"><TabsList><TabsTrigger value="org">Organization</TabsTrigger><TabsTrigger value="members">Members & roles</TabsTrigger><TabsTrigger value="keys">API keys</TabsTrigger><TabsTrigger value="retention">Retention</TabsTrigger></TabsList>
      <TabsContent value="org">{me.data && <Card><CardContent className="grid gap-3 p-5 text-sm md:grid-cols-2">
        <div><div className="text-xs text-muted-foreground">Organization</div><div className="font-medium">{me.data.organizations.find((o: any) => o.id === me.data.organizationId)?.name}</div></div><div><div className="text-xs text-muted-foreground">Your role</div><Badge>{titleCase(me.data.role)}</Badge></div>
        <div><div className="text-xs text-muted-foreground">Destination mode</div><Badge variant={me.data.destinationMode === 'mock' ? 'warning' : 'success'}>{me.data.destinationMode}</Badge> <span className="text-xs text-muted-foreground">(DESTINATION_MODE env)</span></div>
        <div className="md:col-span-2"><div className="text-xs text-muted-foreground">Your permissions</div><div className="mt-1 flex flex-wrap gap-1">{me.data.permissions.map((p: string) => <Badge key={p} variant="muted">{p}</Badge>)}</div></div>
      </CardContent></Card>}</TabsContent>
      <TabsContent value="members"><div className="grid gap-4 lg:grid-cols-3"><Card className="lg:col-span-2"><CardContent className="p-0"><Table><TableHeader><TableRow><TableHead className="pl-5">User</TableHead><TableHead>Role</TableHead><TableHead>Last login</TableHead><TableHead>Member since</TableHead></TableRow></TableHeader><TableBody>{members.data?.data.map((m) => <TableRow key={m.id}><TableCell className="pl-5"><div className="font-medium">{m.name}</div><div className="text-xs text-muted-foreground">{m.email}</div></TableCell><TableCell><Badge variant="outline">{titleCase(m.role)}</Badge></TableCell><TableCell className="text-xs text-muted-foreground">{timeAgo(m.last_login_at)}</TableCell><TableCell className="text-xs text-muted-foreground">{fmtDate(m.created_at)}</TableCell></TableRow>)}</TableBody></Table></CardContent></Card>
        <Card><CardHeader><CardTitle>Add member</CardTitle><CardDescription>Roles: ADMIN, MARKETING_MANAGER, CAMPAIGN_MANAGER, ANALYST, VIEW_ONLY</CardDescription></CardHeader><CardContent className="space-y-2"><Input placeholder="Email" value={inv.email} onChange={(e) => setInv({ ...inv, email: e.target.value })} /><Input placeholder="Name" value={inv.name} onChange={(e) => setInv({ ...inv, name: e.target.value })} /><select className="h-9 w-full rounded-md border bg-background px-2 text-sm" value={inv.role} onChange={(e) => setInv({ ...inv, role: e.target.value })}>{['ADMIN', 'MARKETING_MANAGER', 'CAMPAIGN_MANAGER', 'ANALYST', 'VIEW_ONLY'].map((r) => <option key={r} value={r}>{titleCase(r)}</option>)}</select><Input type="password" placeholder="Initial password (10+ chars)" value={inv.password} onChange={(e) => setInv({ ...inv, password: e.target.value })} /><Button className="w-full" onClick={async () => { try { await apiFetch('/api/v1/settings/members', { method: 'POST', json: inv }); setInvMsg('Member added'); setInv({ email: '', name: '', role: 'ANALYST', password: '' }); members.reload(); } catch (e) { setInvMsg((e as Error).message); } }}>Add</Button>{invMsg && <div className="text-xs text-muted-foreground">{invMsg}</div>}</CardContent></Card></div></TabsContent>
      <TabsContent value="keys"><div className="grid gap-4 lg:grid-cols-3"><Card className="lg:col-span-2"><CardHeader><CardTitle>API keys</CardTitle><CardDescription>Use as <code>Authorization: Bearer aap_…</code> for POST /api/v1/events and /customers. Keys are stored hashed.</CardDescription></CardHeader><CardContent className="p-0"><Table><TableHeader><TableRow><TableHead className="pl-5">Name</TableHead><TableHead>Prefix</TableHead><TableHead>Scopes</TableHead><TableHead>Last used</TableHead><TableHead>Status</TableHead><TableHead /></TableRow></TableHeader><TableBody>
        {keys.data?.data.map((k) => <TableRow key={k.id}><TableCell className="pl-5 font-medium">{k.name}</TableCell><TableCell className="font-mono text-xs">{k.key_prefix}…</TableCell><TableCell className="text-xs">{k.scopes.join(', ')}</TableCell><TableCell className="text-xs text-muted-foreground">{timeAgo(k.last_used_at)}</TableCell><TableCell>{k.revoked_at ? <Badge variant="muted">revoked</Badge> : <Badge variant="success">active</Badge>}</TableCell><TableCell className="text-right">{!k.revoked_at && <Button size="xs" variant="ghost" onClick={async () => { await apiFetch(`/api/v1/settings/api-keys/${k.id}`, { method: 'DELETE' }); keys.reload(); }}>Revoke</Button>}</TableCell></TableRow>)}
        {keys.data && !keys.data.data.length && <TableRow><TableCell colSpan={6} className="py-8 text-center text-xs text-muted-foreground">No API keys</TableCell></TableRow>}</TableBody></Table></CardContent></Card>
        <Card><CardHeader><CardTitle>Create key</CardTitle><CardDescription>Shown once — copy it now.</CardDescription></CardHeader><CardContent className="space-y-3"><div className="space-y-1"><Label>Name</Label><Input value={keyName} onChange={(e) => setKeyName(e.target.value)} placeholder="Shopify webhook relay" /></div><div className="space-y-1"><Label>Scopes</Label><div className="flex flex-wrap gap-1">{SCOPES.map((s) => <button type="button" key={s} onClick={() => setScopes((x) => (x.includes(s) ? x.filter((y) => y !== s) : [...x, s]))} className={`rounded-full border px-2 py-0.5 text-[11px] ${scopes.includes(s) ? 'border-primary bg-accent' : ''}`}>{s}</button>)}</div></div>
          <Button className="w-full" disabled={!keyName || !scopes.length} onClick={async () => { setErr(null); try { setCreated(await apiFetch('/api/v1/settings/api-keys', { method: 'POST', json: { name: keyName, scopes } })); setKeyName(''); keys.reload(); } catch (e) { setErr((e as Error).message); } }}>Create API key</Button>
          {created && <div className="rounded-md border border-success/40 bg-success/10 p-2 text-xs"><div className="font-medium text-success">Copy now — it will not be shown again</div><code className="mt-1 block break-all font-mono">{created.key}</code></div>}<ErrorBox message={err} /></CardContent></Card></div></TabsContent>
      <TabsContent value="retention"><Card><CardHeader><CardTitle>Retention policies</CardTitle><CardDescription>Organization-configurable. The daily maintenance job drops expired partitions (events, carts, membership history, sync batches) and deletes expired rows. Legal periods are not hard-coded.</CardDescription></CardHeader><CardContent>
        {ret.loading ? <LoadingRows /> : <div className="grid gap-3 md:grid-cols-2 lg:grid-cols-4">{ret.data?.data.map((r) => <div key={r.data_class} className="space-y-1"><Label>{titleCase(r.data_class)} (days)</Label><Input type="number" min={1} value={retDraft[r.data_class] ?? r.retention_days} onChange={(e) => setRetDraft({ ...retDraft, [r.data_class]: Number(e.target.value) })} /></div>)}</div>}
        <div className="mt-4 flex items-center gap-3"><Button disabled={!Object.keys(retDraft).length} onClick={async () => { try { await apiFetch('/api/v1/settings/retention', { method: 'PATCH', json: { policies: Object.entries(retDraft).map(([dataClass, retentionDays]) => ({ dataClass, retentionDays })) } }); setRetMsg('Saved'); setRetDraft({}); ret.reload(); } catch (e) { setRetMsg((e as Error).message); } }}>Save</Button>{retMsg && <span className="text-xs text-muted-foreground">{retMsg}</span>}</div>
      </CardContent></Card></TabsContent>
    </Tabs>
  </div>);
}
