/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type ArrayType<T> = ArrayTypeImpl<T> extends (infer U)[]
  ? U[]
  : ArrayTypeImpl<T>;

export type ArrayTypeImpl<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S[], I[], U[]>
  : T[];

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<number, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<number, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface ApiKeys {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  expires_at: Timestamp | null;
  id: Generated<string>;
  key_hash: Buffer;
  key_prefix: string;
  last_used_at: Timestamp | null;
  name: string;
  organization_id: string;
  revoked_at: Timestamp | null;
  scopes: Generated<string[]>;
}

export interface AudienceDestinationMembers {
  added_at: Timestamp | null;
  attempts: Generated<number>;
  audience_destination_id: string;
  customer_id: Int8;
  identifier_kinds: Generated<string[]>;
  last_attempt_at: Timestamp | null;
  last_error_code: string | null;
  last_sync_job_id: string | null;
  removed_at: Timestamp | null;
  state: string;
  updated_at: Generated<Timestamp>;
}

export interface AudienceDestinations {
  audience_id: string;
  compliance_policy_id: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  destination_account_id: string;
  eligible_count: Generated<Int8>;
  external_audience_id: string | null;
  external_audience_name: string | null;
  id: Generated<string>;
  last_error: string | null;
  last_sync_job_id: string | null;
  last_synced_at: Timestamp | null;
  match_rate: Numeric | null;
  matched_count: Int8 | null;
  matched_lower: Int8 | null;
  matched_upper: Int8 | null;
  next_sync_at: Timestamp | null;
  organization_id: string;
  platform_status: Generated<Json>;
  source_count: Generated<Int8>;
  status: Generated<string>;
  submitted_count: Generated<Int8>;
  sync_mode: Generated<string>;
  sync_schedule: string | null;
  updated_at: Generated<Timestamp>;
}

export interface AudienceEvalRuns {
  audience_id: string;
  candidates: Generated<Int8>;
  duration_ms: number | null;
  entered: Generated<Int8>;
  error: string | null;
  exited: Generated<Int8>;
  finished_at: Timestamp | null;
  id: Generated<string>;
  mode: string;
  organization_id: string;
  rule_version: number;
  started_at: Generated<Timestamp>;
  status: Generated<string>;
  watermark_from: Timestamp | null;
  watermark_to: Timestamp | null;
}

export interface AudienceExclusions {
  audience_id: string;
  created_at: Generated<Timestamp>;
  excluded_audience_id: string;
}

export interface AudienceMembers {
  audience_id: string;
  customer_id: Int8;
  entered_at: Timestamp;
  exited_at: Timestamp | null;
  is_primary: Generated<boolean>;
  last_evaluated_at: Timestamp;
  organization_id: string;
  rule_version: number;
  status: Generated<string>;
}

export interface AudienceMembershipHistory {
  action: string;
  audience_id: string;
  customer_id: Int8;
  eval_run_id: string | null;
  id: Generated<Int8>;
  occurred_at: Generated<Timestamp>;
  organization_id: string;
  reason: string | null;
  rule_version: number | null;
}

export interface AudienceOutcomesDaily {
  audience_id: string;
  converters: Generated<Int8>;
  customers: Generated<Int8>;
  day: Timestamp;
  group: string;
  orders: Generated<Int8>;
  revenue: Generated<Numeric>;
}

export interface AudienceRules {
  audience_id: string;
  compiled_sql: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  definition: Json;
  id: Generated<string>;
  version: number;
}

export interface Audiences {
  added_today: Generated<Int8>;
  archived_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  current_rule_version: Generated<number>;
  description: Generated<string>;
  distribution_policy: Generated<Json>;
  eligible_count: Generated<Int8>;
  evaluation_schedule: Generated<string>;
  holdout_percent: Generated<Numeric>;
  holdout_salt: Generated<string>;
  id: Generated<string>;
  last_eval_mode: string | null;
  last_evaluated_at: Timestamp | null;
  member_count: Generated<Int8>;
  name: string;
  next_evaluation_at: Timestamp | null;
  organization_id: string;
  priority: Generated<number>;
  recommendation: Json | null;
  removed_today: Generated<Int8>;
  slug: string;
  status: Generated<string>;
  tags: Generated<string[]>;
  template_key: string | null;
  updated_at: Generated<Timestamp>;
}

export interface AudienceStatsDaily {
  audience_id: string;
  day: Timestamp;
  eligible_count: Generated<Int8>;
  entered: Generated<Int8>;
  exited: Generated<Int8>;
  member_count: Generated<Int8>;
}

export interface AuditLogs {
  action: string;
  actor_id: string | null;
  actor_label: Generated<string>;
  actor_type: string;
  after: Json | null;
  before: Json | null;
  entity_id: string | null;
  entity_type: string | null;
  id: Generated<Int8>;
  ip: string | null;
  metadata: Generated<Json>;
  occurred_at: Generated<Timestamp>;
  organization_id: string;
  user_agent: string | null;
}

export interface CampaignAudiences {
  audience_id: string;
  campaign_id: string;
}

export interface CampaignMetricsDaily {
  campaign_id: string;
  clicks: Generated<Int8>;
  conversion_value: Generated<Numeric>;
  conversions: Generated<Int8>;
  day: Timestamp;
  frequency: Numeric | null;
  impressions: Generated<Int8>;
  reach: Int8 | null;
  spend: Generated<Numeric>;
}

export interface Campaigns {
  created_at: Generated<Timestamp>;
  destination_account_id: string | null;
  end_date: Timestamp | null;
  external_campaign_id: string | null;
  id: Generated<string>;
  name: string;
  objective: string | null;
  organization_id: string;
  start_date: Timestamp | null;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface CartEvents {
  cart_id: string | null;
  customer_id: Int8;
  event_id: string | null;
  event_type: string;
  id: Generated<Int8>;
  occurred_at: Timestamp;
  organization_id: string;
  product_id: Int8 | null;
  quantity: number | null;
  value: Numeric | null;
}

export interface Categories {
  created_at: Generated<Timestamp>;
  external_category_id: string;
  id: Generated<Int8>;
  name: string;
  organization_id: string;
  parent_id: Int8 | null;
  path: string | null;
  updated_at: Generated<Timestamp>;
}

export interface CompliancePolicies {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  destination_type: string | null;
  id: Generated<string>;
  is_default: Generated<boolean>;
  name: string;
  organization_id: string;
  rules: Json;
  updated_at: Generated<Timestamp>;
}

export interface ConsentEvents {
  customer_id: Int8;
  event_id: string | null;
  event_type: string;
  evidence: Json | null;
  id: Generated<Int8>;
  jurisdiction: string | null;
  legal_basis: string | null;
  occurred_at: Timestamp;
  organization_id: string;
  purposes: Generated<Json>;
  recorded_at: Generated<Timestamp>;
  source: string | null;
}

export interface CustomerAdExposure {
  clicks_7d: Generated<number>;
  customer_id: Int8;
  destination_type: string;
  frequency_7d: Numeric | null;
  impressions_7d: Generated<number>;
  last_click_at: Timestamp | null;
  last_conversion_at: Timestamp | null;
  last_impression_at: Timestamp | null;
  organization_id: string;
  updated_at: Generated<Timestamp>;
}

export interface CustomerCategoryPurchases {
  category_id: Int8;
  customer_id: Int8;
  first_purchased_at: Timestamp;
  last_purchased_at: Timestamp;
  organization_id: string;
  purchase_count: Generated<number>;
  revenue: Generated<Numeric>;
}

export interface CustomerEvents {
  customer_id: Int8 | null;
  event_id: string;
  event_type: string;
  external_customer_id: string | null;
  id: Generated<Int8>;
  occurred_at: Timestamp;
  organization_id: string;
  payload: Generated<Json>;
  payload_hash: Buffer;
  processed_at: Timestamp | null;
  processing_error: string | null;
  processing_status: Generated<string>;
  received_at: Generated<Timestamp>;
  source: string | null;
}

export interface CustomerIdentifiers {
  customer_id: Int8;
  hash: Buffer;
  hash_profile: string;
  kind: string;
  organization_id: string;
  updated_at: Generated<Timestamp>;
}

export interface CustomerProductInteractions {
  count: Generated<number>;
  customer_id: Int8;
  first_at: Timestamp;
  interaction: string;
  last_at: Timestamp;
  organization_id: string;
  product_id: Int8;
}

export interface CustomerProductPurchases {
  customer_id: Int8;
  first_purchased_at: Timestamp;
  last_purchased_at: Timestamp;
  organization_id: string;
  product_id: Int8;
  purchase_count: Generated<number>;
  quantity: Generated<number>;
  revenue: Generated<Numeric>;
}

export interface Customers {
  advertising_personalization_allowed: Generated<boolean>;
  attributes: Generated<Json>;
  average_order_value: Generated<Numeric>;
  cancelled_count: Generated<number>;
  cart_event_count: Generated<number>;
  city: string | null;
  consent_status: Generated<string>;
  consent_updated_at: Timestamp | null;
  country: string | null;
  created_at: Generated<Timestamp>;
  data_sharing_allowed: Generated<boolean>;
  deleted: Generated<boolean>;
  deleted_at: Timestamp | null;
  email_encrypted: Buffer | null;
  email_hash: Buffer | null;
  email_valid: boolean | null;
  external_customer_id: string | null;
  first_order_at: Timestamp | null;
  has_open_cart: Generated<boolean>;
  id: Generated<Int8>;
  last_activity_at: Timestamp | null;
  last_cart_at: Timestamp | null;
  last_order_at: Timestamp | null;
  last_product_view_at: Timestamp | null;
  lifecycle_state: Generated<string>;
  lifecycle_state_changed_at: Timestamp | null;
  lifetime_value: Generated<Numeric>;
  marketing_allowed: Generated<boolean>;
  open_cart_id: string | null;
  order_count: Generated<number>;
  organization_id: string;
  phone_encrypted: Buffer | null;
  phone_hash: Buffer | null;
  phone_valid: boolean | null;
  purchase_frequency_days: Numeric | null;
  refund_amount: Generated<Numeric>;
  refund_count: Generated<number>;
  region: string | null;
  source: string | null;
  source_updated_at: Timestamp | null;
  status: Generated<string>;
  suppressed: Generated<boolean>;
  suppressed_at: Timestamp | null;
  total_revenue: Generated<Numeric>;
  updated_at: Generated<Timestamp>;
}

export interface DataQualitySnapshots {
  checks: Json;
  computed_at: Generated<Timestamp>;
  id: Generated<Int8>;
  organization_id: string;
  score: Numeric;
}

export interface DataSources {
  config: Generated<Json>;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  credential_ref: string | null;
  id: Generated<string>;
  last_run_at: Timestamp | null;
  name: string;
  organization_id: string;
  schedule: string | null;
  status: Generated<string>;
  type: string;
  updated_at: Generated<Timestamp>;
}

export interface DeletionRequests {
  completed_at: Timestamp | null;
  customer_id: Int8 | null;
  details: Generated<Json>;
  id: Generated<string>;
  identifier_hash: Buffer | null;
  identifier_kind: string | null;
  organization_id: string;
  requested_at: Generated<Timestamp>;
  requested_by: string | null;
  status: Generated<string>;
}

export interface DestinationAccounts {
  created_at: Generated<Timestamp>;
  currency: string | null;
  destination_id: string;
  external_account_id: string;
  id: Generated<string>;
  is_default: Generated<boolean>;
  metadata: Generated<Json>;
  name: string;
  organization_id: string;
  status: Generated<string>;
  timezone: string | null;
  updated_at: Generated<Timestamp>;
}

export interface Destinations {
  config: Generated<Json>;
  connection_status: Generated<Json>;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  credential_ref: string | null;
  id: Generated<string>;
  last_error: string | null;
  last_sync_at: Timestamp | null;
  last_tested_at: Timestamp | null;
  name: string;
  organization_id: string;
  status: Generated<string>;
  type: string;
  updated_at: Generated<Timestamp>;
}

export interface HoldoutAssignments {
  assigned_at: Generated<Timestamp>;
  audience_id: string;
  customer_id: Int8;
  group: string;
}

export interface IdentityHistory {
  customer_id: Int8;
  id: Generated<Int8>;
  kind: string;
  new_hash: Buffer | null;
  occurred_at: Generated<Timestamp>;
  organization_id: string;
  previous_hash: Buffer | null;
  reason: string | null;
  source: string | null;
}

export interface IngestionRuns {
  checkpoint: Generated<Json>;
  data_source_id: string | null;
  errors: Generated<Json>;
  events_emitted: Generated<Int8>;
  finished_at: Timestamp | null;
  id: Generated<string>;
  organization_id: string;
  rows_read: Generated<Int8>;
  rows_rejected: Generated<Int8>;
  rows_upserted: Generated<Int8>;
  started_at: Generated<Timestamp>;
  status: Generated<string>;
  triggered_by: string | null;
}

export interface JobQueue {
  attempts: Generated<number>;
  completed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  idempotency_key: string | null;
  last_error: string | null;
  lease_seconds: Generated<number>;
  locked_at: Timestamp | null;
  locked_by: string | null;
  max_attempts: Generated<number>;
  name: string;
  payload: Generated<Json>;
  priority: Generated<number>;
  queue: string;
  run_at: Generated<Timestamp>;
  status: Generated<string>;
}

export interface OrderItems {
  category_id: Int8 | null;
  customer_id: Int8;
  id: Generated<Int8>;
  order_id: Int8;
  ordered_at: Timestamp;
  organization_id: string;
  product_id: Int8 | null;
  quantity: Generated<number>;
  total: Generated<Numeric>;
  unit_price: Generated<Numeric>;
}

export interface Orders {
  cancelled_at: Timestamp | null;
  cart_id: string | null;
  created_at: Generated<Timestamp>;
  currency: Generated<string>;
  customer_id: Int8;
  discount: Generated<Numeric>;
  external_order_id: string;
  id: Generated<Int8>;
  item_count: Generated<number>;
  ordered_at: Timestamp;
  organization_id: string;
  refunded_amount: Generated<Numeric>;
  refunded_at: Timestamp | null;
  source: string | null;
  status: Generated<string>;
  subtotal: Generated<Numeric>;
  total: Generated<Numeric>;
  updated_at: Generated<Timestamp>;
}

export interface OrganizationMembers {
  created_at: Generated<Timestamp>;
  organization_id: string;
  role: string;
  user_id: string;
}

export interface Organizations {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  settings: Generated<Json>;
  slug: string;
  updated_at: Generated<Timestamp>;
}

export interface OrganizationStats {
  computed_at: Generated<Timestamp>;
  duration_ms: number | null;
  organization_id: string;
  stats: Json;
}

export interface ProductRelationships {
  kind: string;
  organization_id: string;
  product_id: Int8;
  related_product_id: Int8;
  replenish_days: number | null;
  weight: Generated<Numeric>;
}

export interface Products {
  active: Generated<boolean>;
  attributes: Generated<Json>;
  brand: string | null;
  category_id: Int8 | null;
  created_at: Generated<Timestamp>;
  currency: string | null;
  external_product_id: string;
  id: Generated<Int8>;
  name: string;
  organization_id: string;
  price: Numeric | null;
  sku: string | null;
  updated_at: Generated<Timestamp>;
}

export interface RetentionPolicies {
  data_class: string;
  organization_id: string;
  retention_days: number;
  updated_at: Generated<Timestamp>;
}

export interface SchemaMigrations {
  applied_at: Generated<Timestamp>;
  checksum: string;
  name: string;
}

export interface Sessions {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  ip: string | null;
  last_seen_at: Generated<Timestamp>;
  organization_id: string | null;
  token_hash: Buffer;
  user_agent: string | null;
  user_id: string;
}

export interface SuppressionRecords {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  customer_id: Int8 | null;
  expires_at: Timestamp | null;
  id: Generated<Int8>;
  identifier_hash: Buffer | null;
  identifier_kind: string | null;
  note: string | null;
  organization_id: string;
  reason: string;
  revoked_at: Timestamp | null;
  scope: Generated<string>;
  source: string | null;
}

export interface SyncJobBatches {
  attempts: Generated<number>;
  created_at: Generated<Timestamp>;
  customer_ids: ArrayType<Int8>;
  error_code: string | null;
  error_message: string | null;
  external_ref: string | null;
  finished_at: Timestamp | null;
  id: Generated<Int8>;
  member_count: number;
  next_attempt_at: Timestamp | null;
  operation: string;
  organization_id: string;
  response_summary: Json | null;
  seq: number;
  started_at: Timestamp | null;
  status: Generated<string>;
  sync_job_id: string;
}

export interface SyncJobs {
  added: Generated<Int8>;
  audience_destination_id: string;
  audience_id: string;
  batches_done: Generated<number>;
  batches_total: Generated<number>;
  checkpoint: Generated<Json>;
  consent_denied_count: Generated<Int8>;
  consent_expired_count: Generated<Int8>;
  consent_unknown_count: Generated<Int8>;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  destination_account_id: string;
  eligible_count: Generated<Int8>;
  error: string | null;
  excluded_by_audience: Generated<Int8>;
  failed: Generated<Int8>;
  finished_at: Timestamp | null;
  holdout_count: Generated<Int8>;
  id: Generated<string>;
  idempotency_key: string | null;
  mode: string;
  no_identifier_count: Generated<Int8>;
  organization_id: string;
  records_evaluated: Generated<Int8>;
  removed: Generated<Int8>;
  skipped: Generated<Int8>;
  source_count: Generated<Int8>;
  started_at: Timestamp | null;
  status: Generated<string>;
  suppressed_count: Generated<Int8>;
  trigger: string;
  warnings: Generated<Json>;
}

export interface Users {
  created_at: Generated<Timestamp>;
  disabled_at: Timestamp | null;
  email: string;
  id: Generated<string>;
  is_super_admin: Generated<boolean>;
  last_login_at: Timestamp | null;
  name: Generated<string>;
  password_hash: string | null;
  updated_at: Generated<Timestamp>;
}

export interface WebhookDeliveries {
  attempts: Generated<number>;
  created_at: Generated<Timestamp>;
  delivered_at: Timestamp | null;
  endpoint_id: string;
  event_type: string;
  id: Generated<Int8>;
  last_error: string | null;
  payload: Json;
  status: Generated<string>;
}

export interface WebhookEndpoints {
  active: Generated<boolean>;
  created_at: Generated<Timestamp>;
  events: string[];
  id: Generated<string>;
  organization_id: string;
  secret_ref: string | null;
  url: string;
}

export interface DB {
  api_keys: ApiKeys;
  audience_destination_members: AudienceDestinationMembers;
  audience_destinations: AudienceDestinations;
  audience_eval_runs: AudienceEvalRuns;
  audience_exclusions: AudienceExclusions;
  audience_members: AudienceMembers;
  audience_membership_history: AudienceMembershipHistory;
  audience_outcomes_daily: AudienceOutcomesDaily;
  audience_rules: AudienceRules;
  audience_stats_daily: AudienceStatsDaily;
  audiences: Audiences;
  audit_logs: AuditLogs;
  campaign_audiences: CampaignAudiences;
  campaign_metrics_daily: CampaignMetricsDaily;
  campaigns: Campaigns;
  cart_events: CartEvents;
  categories: Categories;
  compliance_policies: CompliancePolicies;
  consent_events: ConsentEvents;
  customer_ad_exposure: CustomerAdExposure;
  customer_category_purchases: CustomerCategoryPurchases;
  customer_events: CustomerEvents;
  customer_identifiers: CustomerIdentifiers;
  customer_product_interactions: CustomerProductInteractions;
  customer_product_purchases: CustomerProductPurchases;
  customers: Customers;
  data_quality_snapshots: DataQualitySnapshots;
  data_sources: DataSources;
  deletion_requests: DeletionRequests;
  destination_accounts: DestinationAccounts;
  destinations: Destinations;
  holdout_assignments: HoldoutAssignments;
  identity_history: IdentityHistory;
  ingestion_runs: IngestionRuns;
  job_queue: JobQueue;
  order_items: OrderItems;
  orders: Orders;
  organization_members: OrganizationMembers;
  organization_stats: OrganizationStats;
  organizations: Organizations;
  product_relationships: ProductRelationships;
  products: Products;
  retention_policies: RetentionPolicies;
  schema_migrations: SchemaMigrations;
  sessions: Sessions;
  suppression_records: SuppressionRecords;
  sync_job_batches: SyncJobBatches;
  sync_jobs: SyncJobs;
  users: Users;
  webhook_deliveries: WebhookDeliveries;
  webhook_endpoints: WebhookEndpoints;
}
