'use client';
import { Suspense, useEffect, useState } from 'react';
import { useSearchParams } from 'next/navigation';
import Link from 'next/link';
import { useApi } from '@/lib/api-client';
import { fmtCompact, fmtMoney, fmtNum, fmtPct } from '@/lib/utils';
import { PageHeader, Stat, Funnel, LoadingRows, ErrorBox } from '@/components/shared/page';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Badge } from '@/components/ui/badge';
import { TrendLines, TrendArea } from '@/components/charts/charts';

export default function AnalyticsPage() { return <Suspense fallback={<LoadingRows n={8} />}><AnalyticsInner /></Suspense>; }
function AnalyticsInner() {
  const sp = useSearchParams();
  const { data, error, loading } = useApi<any>('/api/v1/analytics/overview');
  const auds = useApi<{ data: any[] }>('/api/v1/audiences');
  const holdoutAuds = (auds.data?.data ?? []).filter((a) => Number(a.holdout_percent) > 0);
  const [holdoutId, setHoldoutId] = useState<string>(sp.get('holdout') ?? '');
  useEffect(() => { if (!holdoutId && holdoutAuds[0]) setHoldoutId(holdoutAuds[0].id); }, [holdoutAuds, holdoutId]);
  const ho = useApi<any>(holdoutId ? `/api/v1/analytics/holdout/${holdoutId}?days=30` : null);
  if (error) return <ErrorBox message={error} />;
  if (loading || !data) return <LoadingRows n={8} />;
  const o = data.overview; const daily = (data.daily as any[]).map((d) => ({ ...d, spend: Number(d.spend), revenue: Number(d.revenue), roas: Number(d.spend) ? Number(d.revenue) / Number(d.spend) : 0 }));
  const f = data.funnel;
  return (<div>
    <PageHeader title="Analytics" description="Platform-attributed performance per audience, the activation funnel (source → eligible → submitted → matched), and first-party holdout incrementality — the number that actually matters." />
    <div className="grid grid-cols-2 gap-3 md:grid-cols-4 xl:grid-cols-8">
      <Stat label="Spend (30d)" value={fmtMoney(o.campaigns30d.spend)} /><Stat label="Revenue (30d)" value={fmtMoney(o.campaigns30d.revenue)} tone="success" /><Stat label="ROAS" value={o.campaigns30d.roas ? `${o.campaigns30d.roas.toFixed(2)}x` : '—'} /><Stat label="Conversions" value={fmtNum(o.campaigns30d.conversions)} />
      <Stat label="CPA" value={o.campaigns30d.conversions ? fmtMoney(o.campaigns30d.spend / o.campaigns30d.conversions) : '—'} /><Stat label="CTR" value={fmtPct(o.campaigns30d.impressions ? (o.campaigns30d.clicks / o.campaigns30d.impressions) * 100 : null, 2)} /><Stat label="CVR" value={fmtPct(o.campaigns30d.cvr)} /><Stat label="Matched reach" value={fmtCompact(f.matched)} hint={`${fmtCompact(f.submitted)} submitted · ${fmtPct(f.submitted ? (f.matched / f.submitted) * 100 : null)} match`} />
    </div>
    <div className="mt-4 grid gap-4 lg:grid-cols-3">
      <Card className="lg:col-span-2"><CardHeader><CardTitle>Spend vs revenue (60 days)</CardTitle></CardHeader><CardContent>{daily.length ? <TrendArea data={daily} series={[{ key: 'spend', label: 'Spend', color: 'hsl(var(--chart-3))' }, { key: 'revenue', label: 'Revenue', color: 'hsl(var(--chart-2))' }]} /> : <div className="text-xs text-muted-foreground">No campaign metrics yet.</div>}</CardContent></Card>
      <Card><CardHeader><CardTitle>Activation funnel</CardTitle><CardDescription>Across active destination audiences</CardDescription></CardHeader><CardContent><Funnel steps={[{ label: 'Source members', value: Number(f.source) }, { label: 'Eligible', value: Number(f.eligible) }, { label: 'Submitted', value: Number(f.submitted) }, { label: 'Matched (est.)', value: Number(f.matched) }]} /><div className="mt-3 text-[11px] text-muted-foreground">Activation rate {fmtPct(f.source ? (f.submitted / f.source) * 100 : null)} · match rate {fmtPct(f.submitted ? (f.matched / f.submitted) * 100 : null)}.</div></CardContent></Card>
    </div>
    <Card className="mt-4"><CardHeader><CardTitle>Per audience (30d)</CardTitle><CardDescription>Platform-attributed numbers — compare with the holdout report below for incrementality.</CardDescription></CardHeader><CardContent className="p-0"><Table><TableHeader><TableRow><TableHead className="pl-5">Audience</TableHead><TableHead className="text-right">Members</TableHead><TableHead className="text-right">Submitted</TableHead><TableHead className="text-right">Matched</TableHead><TableHead className="text-right">Spend</TableHead><TableHead className="text-right">Revenue</TableHead><TableHead className="text-right">ROAS</TableHead><TableHead className="text-right">Conversions</TableHead><TableHead className="text-right">CPA</TableHead><TableHead className="text-right">CTR</TableHead></TableRow></TableHeader><TableBody>
      {(data.perAudience as any[]).map((a) => { const spend = Number(a.spend), rev = Number(a.revenue), conv = Number(a.conversions); return <TableRow key={a.id}><TableCell className="pl-5"><Link href={`/audiences/${a.id}`} className="hover:underline">{a.name}</Link></TableCell><TableCell className="num text-right">{fmtCompact(Number(a.member_count))}</TableCell><TableCell className="num text-right">{fmtCompact(Number(a.submitted))}</TableCell><TableCell className="num text-right">{fmtCompact(Number(a.matched))}</TableCell><TableCell className="num text-right">{fmtMoney(spend)}</TableCell><TableCell className="num text-right">{fmtMoney(rev)}</TableCell><TableCell className="num text-right font-medium">{spend ? `${(rev / spend).toFixed(2)}x` : '—'}</TableCell><TableCell className="num text-right">{fmtNum(conv)}</TableCell><TableCell className="num text-right">{conv ? fmtMoney(spend / conv) : '—'}</TableCell><TableCell className="num text-right">{fmtPct(Number(a.impressions) ? (Number(a.clicks) / Number(a.impressions)) * 100 : null, 2)}</TableCell></TableRow>; })}
    </TableBody></Table></CardContent></Card>
    <Card className="mt-4"><CardHeader className="flex-row items-center justify-between"><div><CardTitle>Holdout / incrementality</CardTitle><CardDescription>Treatment (activated) vs control (never sent) measured on first-party orders — independent of platform attribution.</CardDescription></div><select className="h-9 rounded-md border bg-background px-2 text-sm" value={holdoutId} onChange={(e) => setHoldoutId(e.target.value)}>{holdoutAuds.map((a) => <option key={a.id} value={a.id}>{a.name} ({a.holdout_percent}%)</option>)}{!holdoutAuds.length && <option value="">No audiences with holdout</option>}</select></CardHeader>
      <CardContent>{ho.data ? (<div className="grid gap-4 lg:grid-cols-3">
        {(['treatment', 'control'] as const).map((g) => { const x = ho.data.report[g]; return <div key={g} className="rounded-lg border p-4"><div className="mb-2 flex items-center justify-between text-xs font-medium uppercase tracking-wider text-muted-foreground">{g}<Badge variant={g === 'treatment' ? 'info' : 'muted'}>{fmtCompact(x.customers)} customers</Badge></div><div className="grid grid-cols-2 gap-2 text-sm"><div><div className="text-[11px] text-muted-foreground">Conversion rate</div><div className="num font-semibold">{fmtPct(x.conversionRate * 100, 2)}</div></div><div><div className="text-[11px] text-muted-foreground">Revenue / customer</div><div className="num font-semibold">{fmtMoney(x.revenuePerCustomer)}</div></div><div><div className="text-[11px] text-muted-foreground">Orders</div><div className="num font-semibold">{fmtNum(x.orders)}</div></div><div><div className="text-[11px] text-muted-foreground">AOV</div><div className="num font-semibold">{fmtMoney(x.aov)}</div></div></div></div>; })}
        <div className="rounded-lg border bg-accent/40 p-4"><div className="mb-2 text-xs font-medium uppercase tracking-wider text-muted-foreground">Lift</div><div className="grid grid-cols-2 gap-2 text-sm"><div><div className="text-[11px] text-muted-foreground">Conv. rate lift</div><div className={`num font-semibold ${ho.data.report.lift.conversionRate >= 0 ? 'text-success' : 'text-destructive'}`}>{(ho.data.report.lift.conversionRate * 100).toFixed(2)} pp</div></div><div><div className="text-[11px] text-muted-foreground">Relative</div><div className="num font-semibold">{ho.data.report.lift.relative != null ? fmtPct(ho.data.report.lift.relative * 100) : '—'}</div></div><div><div className="text-[11px] text-muted-foreground">Incremental conversions</div><div className="num font-semibold">{fmtNum(ho.data.report.lift.incrementalConversions)}</div></div><div><div className="text-[11px] text-muted-foreground">Incremental revenue</div><div className="num font-semibold">{fmtMoney(ho.data.report.lift.incrementalRevenue)}</div></div></div><div className={`mt-3 text-[11px] ${ho.data.report.lift.significant ? 'text-success' : 'text-muted-foreground'}`}>{ho.data.report.lift.note} (z = {ho.data.report.lift.zScore.toFixed(2)})</div></div>
        {ho.data.daily?.length > 0 && <div className="lg:col-span-3"><TrendLines data={Object.values((ho.data.daily as any[]).reduce((acc: Record<string, any>, d) => { const k = String(d.day).slice(0, 10); acc[k] = acc[k] ?? { day: k }; acc[k][d.group === 'TREATMENT' ? 'treatment' : 'control'] = d.customers ? (Number(d.converters) / Number(d.customers)) * 100 : 0; return acc; }, {}))} series={[{ key: 'treatment', label: 'Treatment conv. %' }, { key: 'control', label: 'Control conv. %' }]} yFormatter={(v) => `${v.toFixed(2)}%`} height={180} /></div>}
      </div>) : <div className="text-xs text-muted-foreground">{holdoutId ? 'Loading…' : 'Create an audience with a holdout percentage to measure incrementality.'}</div>}</CardContent></Card>
  </div>);
}
